### PR TITLE
Reactivation of connections from state file

### PR DESCRIPTION
**Pull request by denji**
## Branch: reactivation

Implements something silimar to [dynamic segmentation](http://www.internetdownloadmanager.com/support/segmentation.html).
Finished connections will be reactivated on a different segment of file.
* There are no new config file or argument options.
* Added old patch version 0.3 from [here](http://emiraga.wikispaces.com/Axel+Thread+Reactivation+Patch)

Author: Emir Habul (@emiraga)

### CODE REVIEW

**Comment by eribertomota** [comment]
Hi,

Thanks for your pull request. I liked this idea. However, I need an opinion from @sdt because he is adding https/ftps. @sdt, can I accept this pull request?

@emiraga, I got the following error:

text.c: In function ‘print_alternate_output’:
text.c:499:12: error: conflicting type qualifiers for ‘width’
  const int width = 50;
            ^
text.c:497:6: note: previous definition of ‘width’ was here
  int width = get_term_width() - 30;
      ^
Makefile:373: recipe for target 'text.o' failed


Regards,

Eriberto

**Comment by denji** [comment]
@eribertomota Done! rebased code.

**Comment by eribertomota** [comment]
Thanks.

I will go to dinner. I will go back soon and test the changes.

If you have availability, please, help me in this project too:
https://github.com/eribertomota/packit

Regards,

Eriberto


2016-05-28 19:06 GMT-03:00 Denis Denisov <notifications@github.com>:

**Comment by eribertomota** [comment]
Hi,

Worked fine now. A very good implementation. Thanks and congratulations.

I think that you need resend the pull request, using the new code. Please,
add your copyright in headers (use alphabetical order inside year 2016).

@sdt, can you talk about this pull request and your work?

Regards,

Eriberto


2016-05-28 19:15 GMT-03:00 Eriberto <eriberto@eriberto.pro.br>:

**Comment by sdt** [comment]
This patch looks good to me.

I think my ssl code will rebase onto this without any problems.

**Comment by eribertomota** [comment]
Hi @denji ,

I did a test in Debian now. Can you fix the following warnings? Thanks!

make[3]: Entering directory '/tmp/21/axel-2.10/src'
gcc -DHAVE_CONFIG_H -I. -I..  -DLOCALEDIR=\""/usr/share/locale"\" -Wdate-time -D_FORTIFY_SOURCE=2  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -c -o axel.o axel.c
axel.c: In function ‘axel_open’:
axel.c:208:5: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
     read( fd, &axel->conn[i].lastbyte, sizeof( axel->conn[i].lastbyte ) ); // TODO: callback & assert
     ^
axel.c: In function ‘save_state’:
axel.c:607:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
   write( fd, &axel->conn[i].lastbyte, sizeof( axel->conn[i].lastbyte ) );
   ^

**Comment by sdt** [comment]
I noticed those yesterday while I was testing my rebased branch.

Here's a fix: #21

**Comment by eribertomota** [comment]
Thanks a lot! Tested, fixed.

**Pull request merged**
