### PR TITLE
For servers running on port, axel should set port properly.

### PR DESCRIPTION
**Pull request by harshavardhana**
Host header should have a port set properly in accordance
with HTTP RFC2616.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23

### CODE REVIEW

**Comment by mkdadi** [comment]
Hi @harshavardhana, actually the conn->host variable already has the host:port format assigned at beginning of the function, please check the request and response headers.

**Comment by harshavardhana** [comment]
> Hi @harshavardhana, actually the conn->host variable already has the host:port format assigned at beginning of the function, please check the request and response headers.

It is not AFAICS hosts with port are filtered out would you like to see request header?

**Comment by mkdadi** [comment]
@harshavardhana Following is the request header that is being written to socket when I ran
`axel http://www.7-zip.org/a/7za920.zip`.

`GET http://d.7-zip.org:80/a/7za920.zip HTTP/1.0`
`Host: d.7-zip.org:80`
`User-Agent: Axel 2.12 (Linux)`

**Comment by ismaell** [comment]
This adds another bug on top of the current broken behavior (":<port>" gets duplicated when using a proxy). The usage of `conn->host` needs to be fixed first.

**Comment by ordex** [comment]
what is the current status here?

My understanding so far is that:

1. when downloading from a host using a non-80 port, the port is not specified in the 'Host' header
2. there is some kind of bug which duplicates the port when using a proxy. Or is this bug introduced by the proposed patch?

However, I quickly checked and I saw that when using a proxy, axel does not set any 'Host' header at all. I imagine this is expected.

**Comment by ismaell** [comment]
Superseded by PR #78.

**Pull request closed without merging**
